apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/32
    ports:
    - protocol: TCP
      port: 80
